name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t ./lib
        pip install flowlauncher -t ./lib
        Compress-Archive -Path * -DestinationPath Flow.Launcher.Plugin.Choco.zip -Force
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: 'Flow.Launcher.Plugin.Choco.zip'
        generate_release_notes: true
        tag_name: v${{ github.ref_name }}
        name: Release v${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 